# Generated by Django 5.1.3 on 2024-11-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_alter_employee_work_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middlename',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
