# Generated by Django 5.1.3 on 2024-11-07 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('work_id', models.CharField(max_length=25)),
                ('firstname', models.CharField(max_length=25)),
                ('middlename', models.CharField(max_length=25, null=True)),
                ('lastname', models.CharField(max_length=25)),
            ],
        ),
    ]
