# Generated by Django 5.1.3 on 2024-11-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='work_id',
            field=models.IntegerField(default=3810300380, max_length=25),
        ),
    ]
